### ISSUE TITLE
opencv lib

### ISSUE THREAD

**Issue by hanxinyang53** [kaylorchen/rk3588-yolo-demo#1]
Could you please provide the opencv library you used in this project? Thank you very much!

**Comment by kaylorchen** [comment]
> Could you please provide the opencv library you used in this project? Thank you very much!

I just install opencv lib via apt. 
```bash
apt install libopencv-dev
```
If you want more information, you can Build the Cross-Compilation Environment https://github.com/kaylorchen/rk3588_dev_rootfs

I build the project with this rootfs..

**Comment by hanxinyang53** [comment]
> > Could you please provide the opencv library you used in this project? Thank you very much!
> 
> I just install opencv lib via apt.
> 
> ```shell
> apt install libopencv-dev
> ```
> 
> If you want more information, you can Build the Cross-Compilation Environment https://github.com/kaylorchen/rk3588_dev_rootfs
> 
> I build the project with this rootfs..

Thanks.I install opencv via yum but the function 'imshow' reported error,maybe the local source is incomplete,  I will try to install it online.

**Comment by kaylorchen** [comment]
> > > Could you please provide the opencv library you used in this project? Thank you very much!
> > 
> > 
> > I just install opencv lib via apt.
> > ```shell
> > apt install libopencv-dev
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > If you want more information, you can Build the Cross-Compilation Environment https://github.com/kaylorchen/rk3588_dev_rootfs
> > I build the project with this rootfs..
> 
> Thanks.I install opencv via yum but the function 'imshow' reported error,maybe the local source is incomplete, I will try to install it online.

Is your target board's system centos?

**Comment by hanxinyang53** [comment]
no, i use another



---Original---
From: ***@***.***&gt;
Date: Fri, Apr 12, 2024 23:06 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [kaylorchen/rk3588-yolo-demo] opencv lib (Issue #1)




    
Could you please provide the opencv library you used in this project? Thank you very much!
  
I just install opencv lib via apt.
 apt install libopencv-dev
 
If you want more information, you can Build the Cross-Compilation Environment https://github.com/kaylorchen/rk3588_dev_rootfs
 I build the project with this rootfs..
  
Thanks.I install opencv via yum but the function 'imshow' reported error,maybe the local source is incomplete, I will try to install it online.
  
Is your target board's system centos?
