### ISSUE TITLE
延迟问题

### ISSUE THREAD

**Issue by huochen1** [kaylorchen/rk3588-yolo-demo#12]
不知道作者这个程序有没有遇到就是原始图片计数开始到一开始第六帧的时候，结果第一帧才处理完，然后就是会一直相差那么五帧的延迟，但是实时性感觉不会卡

**Comment by kaylorchen** [comment]
你是大概没有理解程序运行的逻辑。你说的是现象，而且就应该是这样。回头自己理解一下程序就好了。
