### ISSUE TITLE
The files in baidu netDisk are not accessible

### ISSUE THREAD

**Issue by mohd109** [kaylorchen/rk3588-yolo-demo#13]
Hi, first of all, thanks a lot for your efforts. I just wanted to mention that the files that you put in the Baidu netdisk are not accessible since it wants registration which is not available with my phone number.

**Comment by kaylorchen** [comment]
i will upload files to Google drive later

**Comment by kaylorchen** [comment]
> Hi, first of all, thanks a lot for your efforts. I just wanted to mention that the files that you put in the Baidu netdisk are not accessible since it wants registration which is not available with my phone number.

https://drive.google.com/drive/folders/1FYluJpdaL-680pipgIQ1zsqqRvNbruEp?usp=sharing

**Comment by mohd109** [comment]
Thank you.
