### ISSUE TITLE
when I execute "make",some error apper 

### ISSUE THREAD

**Issue by gjrtzy** [kaylorchen/rk3588-yolo-demo#2]
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/videofile_demo.dir/build.make:210: videofile_demo] Error 1
make[1]: *** [CMakeFiles/Makefile2:102: CMakeFiles/videofile_demo.dir/all] Error 2

**Comment by kaylorchen** [comment]
你是不是没有看readme。先配置好编译环境吧

**Comment by KelvinHuang66** [comment]
1 
生成toolchain-aarch64.cmake，cmake -DCMAKE_TOOLCHAIN_FILE=/path/to/toolchain-aarch64.cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ..成功，但是执行
make 失败，相同的报错，C++小白求指教
