### ISSUE TITLE
./camera_demo: error while loading shared libraries: libspdlog.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Liablbility** [kaylorchen/rk3588-yolo-demo#20]
(base) firefly@firefly:~/Documents$ ./camera_demo 
./camera_demo: error while loading shared libraries: libspdlog.so.1: cannot open shared object file: No such file or directory

详细的  to be specific

(base) firefly@firefly:~/Documents$ ldd camera_demo 
./camera_demo: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./camera_demo)
./camera_demo: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./camera_demo)
./camera_demo: /lib/aarch64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by ./camera_demo)
./camera_demo: /lib/aarch64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by ./camera_demo)
./camera_demo: /lib/aarch64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.13' not found (required by ./camera_demo)
	linux-vdso.so.1 (0x0000007f8c781000)
	libspdlog.so.1 => not found
	libsystemd.so.0 => /lib/aarch64-linux-gnu/libsystemd.so.0 (0x0000007f8c641000)
	libbytetrack.so.3 => not found
	libfmt.so.8 => not found
	libopencv_highgui.so.4.5d => not found
	libopencv_videoio.so.4.5d => not found
	libopencv_imgproc.so.4.5d => not found
	libopencv_core.so.4.5d => not found
	librknnrt.so => /lib/librknnrt.so (0x0000007f8c2c9000)
	libstdc++.so.6 => /lib/aarch64-linux-gnu/libstdc++.so.6 (0x0000007f8c0e4000)
	libm.so.6 => /lib/aarch64-linux-gnu/libm.so.6 (0x0000007f8c039000)
	libgcc_s.so.1 => /lib/aarch64-linux-gnu/libgcc_s.so.1 (0x0000007f8c015000)
	libc.so.6 => /lib/aarch64-linux-gnu/libc.so.6 (0x0000007f8bea2000)
	/lib/ld-linux-aarch64.so.1 (0x0000007f8c751000)
	librt.so.1 => /lib/aarch64-linux-gnu/librt.so.1 (0x0000007f8be8a000)
	liblzma.so.5 => /lib/aarch64-linux-gnu/liblzma.so.5 (0x0000007f8be56000)
	liblz4.so.1 => /lib/aarch64-linux-gnu/liblz4.so.1 (0x0000007f8be28000)
	libgcrypt.so.20 => /lib/aarch64-linux-gnu/libgcrypt.so.20 (0x0000007f8bd5c000)
	libpthread.so.0 => /lib/aarch64-linux-gnu/libpthread.so.0 (0x0000007f8bd2b000)
	libgpg-error.so.0 => /lib/aarch64-linux-gnu/libgpg-error.so.0 (0x0000007f8bcfb000)

我根据 提示在rknn部署了运行环境 具体的就是以下步骤

Install Runtime Libraries in Your RK3588 Target Board
cat << 'EOF' | sudo tee /etc/apt/sources.list.d/kaylordut.list 
deb [signed-by=/etc/apt/keyrings/kaylor-keyring.gpg] http://apt.kaylordut.cn/kaylordut/ kaylordut main
EOF
sudo mkdir /etc/apt/keyrings -pv
sudo wget -O /etc/apt/keyrings/kaylor-keyring.gpg http://apt.kaylordut.cn/kaylor-keyring.gpg
sudo apt update
sudo apt install kaylordut-dev libbytetrack
If your OS is not Ubuntu22.04, and find kaylordut-dev and libbytetrack sources in my github.
（我编译的pc机是 22.04  但是我rknn设备的是20.04）

**Comment by kaylorchen** [comment]
你这个不是issue。自己根据问题反馈处理吧。
