### ISSUE TITLE
./videofile_demo.cpp: line 12: struct: command not found

### ISSUE THREAD

**Issue by nerbivol** [kaylorchen/rk3588-yolo-demo#4]
I've been setting up a cross-compilation environment for the RK3588 platform using the following steps:

1. Installed the cross-compilation toolchain using the commands:
    ```bash
    sudo apt update
    sudo apt install gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
    ```

2. Built a cross-compilation environment rootfs by cloning the repository:
    ```bash
    git clone https://github.com/kaylorchen/rk3588_dev_rootfs.git
    cd rk3588_dev_rootfs
    bash ./build-rootfs.sh
    ```

3. Compiled my code using the cross-compilation environment with the following commands:
    ```bash
    git clone https://github.com/kaylorchen/rk3588-yolo-demo.git 
    cd rk3588-yolo-demo/src/yolov8
    mkdir build
    cd build
    cmake -DCMAKE_TOOLCHAIN_FILE=/home/orangepi/rk3588_dev_rootfs/toolchain-aarch64.cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ..
    make 
    ```

However, when I attempt to run the `videofile_demo.cpp` script as follows:
```bash
./videofile_demo.cpp --model_path model/yolov8n.rknn --input_filename 720p60hz.mp4 --threads 4 --framerate 60 --label_path model/coco_80_labels_list.txt
```

I encounter the following errors:
```
./videofile_demo.cpp: line 12: struct: command not found
./videofile_demo.cpp: line 13: std::string: command not found
./videofile_demo.cpp: line 14: std::string: command not found
./videofile_demo.cpp: line 15: std::string: command not found
./videofile_demo.cpp: line 16: int: command not found
./videofile_demo.cpp: line 17: double: command not found
./videofile_demo.cpp: line 18: syntax error near unexpected token `}'
./videofile_demo.cpp: line 18: `};'
```

It seems like the script is being interpreted as shell commands instead of C++ code. Any guidance on how to resolve this issue would be greatly appreciated. Thank you!

**Comment by kaylorchen** [comment]
> I've been setting up a cross-compilation environment for the RK3588 platform using the following steps:
> 
> 1. Installed the cross-compilation toolchain using the commands:
>    ```shell
>    sudo apt update
>    sudo apt install gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
>    ```
> 2. Built a cross-compilation environment rootfs by cloning the repository:
>    ```shell
>    git clone https://github.com/kaylorchen/rk3588_dev_rootfs.git
>    cd rk3588_dev_rootfs
>    bash ./build-rootfs.sh
>    ```
> 3. Compiled my code using the cross-compilation environment with the following commands:
>    ```shell
>    git clone https://github.com/kaylorchen/rk3588-yolo-demo.git 
>    cd rk3588-yolo-demo/src/yolov8
>    mkdir build
>    cd build
>    cmake -DCMAKE_TOOLCHAIN_FILE=/home/orangepi/rk3588_dev_rootfs/toolchain-aarch64.cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ..
>    make 
>    ```
> 
> However, when I attempt to run the `videofile_demo.cpp` script as follows:
> 
> ```shell
> ./videofile_demo.cpp --model_path model/yolov8n.rknn --input_filename 720p60hz.mp4 --threads 4 --framerate 60 --label_path model/coco_80_labels_list.txt
> ```
> 
> I encounter the following errors:
> 
> ```
> ./videofile_demo.cpp: line 12: struct: command not found
> ./videofile_demo.cpp: line 13: std::string: command not found
> ./videofile_demo.cpp: line 14: std::string: command not found
> ./videofile_demo.cpp: line 15: std::string: command not found
> ./videofile_demo.cpp: line 16: int: command not found
> ./videofile_demo.cpp: line 17: double: command not found
> ./videofile_demo.cpp: line 18: syntax error near unexpected token `}'
> ./videofile_demo.cpp: line 18: `};'
> ```
> 
> It seems like the script is being interpreted as shell commands instead of C++ code. Any guidance on how to resolve this issue would be greatly appreciated. Thank you!

./videofile_demo.cpp is  a cpp file, not a script. 
If you build the project successfully, you can find a exetalble file named "videofile_demo" in the build folder....
this is a cpp project.... not python

**Comment by nerbivol** [comment]
Yes, that's true.

But I get the next error. Upon running the provided command:

```bash
orangepi@orangepi5b:~/rk3588-yolo-demo/src/yolov8/build$ ./videofile_demo --model_path ../model/yolov8n.rknn --input_filename ../720p60hz.mp4 --threads 4 --framerate 60 --label_path ../model/coco_80_labels_list.txt
```

I encountered the following error:

```
environment variable SPDLOG_STDOUT is not set, and set true
environment variable SPDLOG_SYSTEMD is not set, and set false
environment variable SPDLOG_LEVEL is not set, and set default level
[INFO] Yolov8 demo for rk3588
[INFO] load lable ../model/coco_80_labels_list.txt
[ERROR] Open ../model/coco_80_labels_list.txt fail!
[INFO] fopen ../model/yolov8n.rknn failed!
[INFO] rknn_init() is called
E RKNN: [21:50:04.121] parseRKNN: invalid RKNN_MAGIC!
E RKNN: [21:50:04.121] parseRKNN from buffer: Invalid RKNN format!
E RKNN: [21:50:04.121] rknn_init, load model failed!
Segmentation fault (core dumped)
```

It seems that several environment variables related to logging (`SPDLOG_STDOUT`, `SPDLOG_SYSTEMD`, and `SPDLOG_LEVEL`) were not set, but defaulted to certain values.

**Comment by kaylorchen** [comment]
> Yes, that's true.
> 
> But I get the next error. Upon running the provided command:
> 
> ```shell
> orangepi@orangepi5b:~/rk3588-yolo-demo/src/yolov8/build$ ./videofile_demo --model_path ../model/yolov8n.rknn --input_filename ../720p60hz.mp4 --threads 4 --framerate 60 --label_path ../model/coco_80_labels_list.txt
> ```
> 
> I encountered the following error:
> 
> ```
> environment variable SPDLOG_STDOUT is not set, and set true
> environment variable SPDLOG_SYSTEMD is not set, and set false
> environment variable SPDLOG_LEVEL is not set, and set default level
> [INFO] Yolov8 demo for rk3588
> [INFO] load lable ../model/coco_80_labels_list.txt
> [ERROR] Open ../model/coco_80_labels_list.txt fail!
> [INFO] fopen ../model/yolov8n.rknn failed!
> [INFO] rknn_init() is called
> E RKNN: [21:50:04.121] parseRKNN: invalid RKNN_MAGIC!
> E RKNN: [21:50:04.121] parseRKNN from buffer: Invalid RKNN format!
> E RKNN: [21:50:04.121] rknn_init, load model failed!
> Segmentation fault (core dumped)
> ```
> 
> It seems that several environment variables related to logging (`SPDLOG_STDOUT`, `SPDLOG_SYSTEMD`, and `SPDLOG_LEVEL`) were not set, but defaulted to certain values.

check your file's path. 
```
[INFO] load lable ../model/coco_80_labels_list.txt
[ERROR] Open ../model/coco_80_labels_list.txt fail!
[INFO] fopen ../model/yolov8n.rknn failed!
```
I think you entered a wrong path

**Comment by nerbivol** [comment]
Here's the folder tree structure based on the provided directory listings:

```
rk3588-yolo-demo
└── src
    └── yolov8
        ├── 720p60hz.mp4
        ├── build
        │   ├── build
        │   ├── CMakeCache.txt
        │   ├── cmake_install.cmake
        │   ├── compile_commands.json
        │   ├── Makefile
        │   └── videofile_demo
        ├── camera_demo.cpp
        ├── CMakeLists.txt
        ├── include
        ├── model
        │   ├── coco_80_labels_list.txt
        │   ├── yolov8m.rknn
        │   ├── yolov8n.rknn
        │   └── yolov8s.rknn
        ├── utils
        └── videofile_demo.cpp
```

**Comment by kaylorchen** [comment]
> Here's the folder tree structure based on the provided directory listings:
> 
> ```
> rk3588-yolo-demo
> └── src
>     └── yolov8
>         ├── 720p60hz.mp4
>         ├── build
>         │   ├── build
>         │   ├── CMakeCache.txt
>         │   ├── cmake_install.cmake
>         │   ├── compile_commands.json
>         │   ├── Makefile
>         │   └── videofile_demo
>         ├── camera_demo.cpp
>         ├── CMakeLists.txt
>         ├── include
>         ├── model
>         │   ├── coco_80_labels_list.txt
>         │   ├── yolov8m.rknn
>         │   ├── yolov8n.rknn
>         │   └── yolov8s.rknn
>         ├── utils
>         └── videofile_demo.cpp
> ```

Dose the command run in your rk3588?  
log error: [ERROR] Open ../model/coco_80_labels_list.txt fail!,  I suggest you double check your path to read files.

You have an error opening the file here. Check whether the path is correct, or check whether the file has read permission.

**Comment by nerbivol** [comment]
It's strange. Right now, the same command is working, but it's showing incorrect results, and my Orange Pi is freezing. Do you have any recommendations on what parameters to set for --threads and --framerate?

**Comment by kaylorchen** [comment]
> It's strange. Right now, the same command is working, but it's showing incorrect results, and my Orange Pi is freezing. Do you have any recommendations on what parameters to set for --threads and --framerate?

Set it to 1 first, then increase from small to large.

**Comment by nerbivol** [comment]
Thank you. It is working now

**Comment by nerbivol** [comment]
Only if I set --threads more than 1, it works badly

**Comment by kaylorchen** [comment]
> Only if I set --threads more than 1, it works badly

it works well in my orangepi 5 Plus. I think you should check your npu driver version and .so lib version.
