### ISSUE TITLE
代码仓库里缺少头文件和库

### ISSUE THREAD

**Issue by lostarcher** [kaylorchen/rk3588-yolo-demo#5]
主文件包含的
#include "getopt.h"
#include "kaylordut/log/logger.h"
#include "kaylordut/time/time_duration.h"
#include "kaylordut/time/timeout.h"
这几个头文件没有，对应的库文件也没有，能补一下吗？

**Comment by kaylorchen** [comment]
> 主文件包含的 #include "getopt.h" #include "kaylordut/log/logger.h" #include "kaylordut/time/time_duration.h" #include "kaylordut/time/timeout.h" 这几个头文件没有，对应的库文件也没有，能补一下吗？

仔细阅读readme

**Comment by lostarcher** [comment]
看到了，谢谢
