### ISSUE TITLE
两次推理同一个模型帧数不一致

### ISSUE THREAD

**Issue by gjrtzy** [kaylorchen/rk3588-yolo-demo#6]
模型、线程数都一样，两次推理一个帧数4npu占用率8%左右，一个21npu占用率55-60

**Comment by kaylorchen** [comment]
> 模型、线程数都一样，两次推理一个帧数4npu占用率8%左右，一个21npu占用率55-60

可能需要你自己看看什么问题，我这里没有发现这些问题。注意你自己的npu驱动版本和so的版本

**Comment by gjrtzy** [comment]
> > 模型、线程数都一样，两次推理一个帧数4npu占用率8%左右，一个21npu占用率55-60
> 
> 可能需要你自己看看什么问题，我这里没有发现这些问题。注意你自己的npu驱动版本和so的版本
能推理了，我一开始用的远程登录，换成直接在在板子上运行就稳定29帧

**Comment by kaylorchen** [comment]
> > > 模型、线程数都一样，两次推理一个帧数4npu占用率8%左右，一个21npu占用率55-60
> > 
> > 
> > 可能需要你自己看看什么问题，我这里没有发现这些问题。注意你自己的npu驱动版本和so的版本
> > 能推理了，我一开始用的远程登录，换成直接在在板子上运行就稳定29帧

使用的无线吧，我视频里提过一嘴。本地网络波动不能这么玩的。我录视频可以这么做是因为我用的有线的，带宽都占用了600M

**Comment by gjrtzy** [comment]
> > > > 模型、线程数都一样，两次推理一个帧数4npu占用率8%左右，一个21npu占用率55-60
> > > 
> > > 
> > > 可能需要你自己看看什么问题，我这里没有发现这些问题。注意你自己的npu驱动版本和so的版本
> > > 能推理了，我一开始用的远程登录，换成直接在在板子上运行就稳定29帧
> 
> 使用的无线吧，我视频里提过一嘴。本地网络波动不能这么玩的。我录视频可以这么做是因为我用的有线的，带宽都占用了600M

是的
