### ISSUE TITLE
Add capability for another input image size

### ISSUE THREAD

**Issue by IrDIE** [kaylorchen/rk3588-yolo-demo#7]
Hi, thank you for your work
I noticed that current version support only 640*640 input image size. Can you share what to do to use that repo for another image size (what yolo8 was trained on)

And can you give some explanation why this values are 160?:

```
#define PROTO_HEIGHT  (160)
#define PROTO_WEIGHT (160)
```

**Comment by kaylorchen** [comment]
This is just a demo. I suggest you refer to my example to create your own project. The reason for using 160x160 is because the output layer size of YOLOv8's proto is 160x160.

**Comment by IrDIE** [comment]
@kaylorchen 
I found that 160 x 160 proto used only for segmentation YOLO models. Detection models outputs are shape(1, 84, 8400) (for 640*640 input imgsize and 80cls). What should I change in your code to use that for Detection model and another input image-size?

**Comment by kaylorchen** [comment]
> @kaylorchen I found that 160 x 160 proto used only for segmentation YOLO models. Detection models outputs are shape(1, 84, 8400) (for 640*640 input imgsize and 80cls). What should I change in your code to use that for Detection model and another input image-size?
"You should not modify my code, but rather adjust the model's output. because the official model includes some post-processing calculations, the matrix operations of which exceed the maximum matrix calculation size of the 3588 NPU."

**Comment by IrDIE** [comment]
@kaylorchen 
For 800*800 input image size - do I need to change this - https://github.com/kaylorchen/rk3588-yolo-demo/blob/0c8c652771e731a84dd036bf064a8ab1972ac48e/src/yolov8/utils/postprocess.cpp#L737-L739 ?

and implement it like:
```
// 800 / 160 = 5.0
filterBoxes_by_nms[i * 4 + 0] =
        od_results->results[i].box.left / 5.0;  // x1;
```

**Comment by kaylorchen** [comment]
I'm confused by your input.
If the project's image is 800*800, I will resize it to 640*640, and I get 160*160 mask image for 640*640 input. Finally I converted the coordinates into the original 800*800 image.

**Comment by IrDIE** [comment]
@kaylorchen 
But I wanna resize input image of any size not to 640, but to 800. And pass that 800x800 image to rknn-model graph
![image](https://github.com/kaylorchen/rk3588-yolo-demo/assets/110756720/088e87e1-5bb2-4d9a-8ed5-c6b76af729cb)

please check the screenshot to understand how my rknn-model outputs looks like
