### ISSUE TITLE
如果分辨率变成1920*1080的话会出现目标框和物体不在同一个位置，会有偏移，分辨率640*480的话是正常的

### ISSUE THREAD

**Issue by huochen1** [kaylorchen/rk3588-yolo-demo#8]

**Comment by huochen1** [comment]
如果分辨率变成1920*1080的话会出现目标框和物体不在同一个位置，会有偏移，分辨率640*480的话是正常的

**Comment by kaylorchen** [comment]
> 如果分辨率变成1920_1080的话会出现目标框和物体不在同一个位置，会有偏移，分辨率640_480的话是正常的

可能是你设置的问题，我这里设置的都没有什么问题。
